In [1]:
# from google.colab import drive
# drive.mount('/content/gdrive')

In [2]:
# from google.colab import files
# files.upload()

# Service Disruption

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [4]:
train = pd.read_csv('train.csv')
evn = pd.read_csv('event_type.csv')
log = pd.read_csv('log_feature.csv')
res = pd.read_csv('resource_type.csv')
sev = pd.read_csv('severity_type.csv')

## EDA - Exploratory Data Analysis

In [5]:
train.shape, evn.shape, log.shape, res.shape, sev.shape

((7381, 3), (31170, 2), (58671, 3), (21076, 2), (18552, 2))

In [6]:
train.head()

id      location  fault_severity
0  14121  location 118               1
1   9320   location 91               0
2  14394  location 152               1
3   8218  location 931               1
4  14804  location 120               0

In [7]:
evn.head()

id     event_type
0  6597  event_type 11
1  8011  event_type 15
2  2597  event_type 15
3  5022  event_type 15
4  5022  event_type 11

In [8]:
log.head()

id  log_feature  volume
0  6597   feature 68       6
1  8011   feature 68       7
2  2597   feature 68       1
3  5022  feature 172       2
4  5022   feature 56       1

In [9]:
res.head()

id    resource_type
0  6597  resource_type 8
1  8011  resource_type 8
2  2597  resource_type 8
3  5022  resource_type 8
4  6852  resource_type 8

In [10]:
sev.head()

id    severity_type
0  6597  severity_type 2
1  8011  severity_type 2
2  2597  severity_type 2
3  5022  severity_type 1
4  6852  severity_type 1

In [11]:
Train = train.merge(sev, how = "left", left_on = "id", right_on = "id")
Train = Train.merge(evn, how = "left", left_on = "id", right_on = "id")
Train = Train.merge(log, how = "left", left_on = "id", right_on = "id")
Train = Train.merge(res, how = "left", left_on = "id", right_on = "id")

In [12]:
Train.head()

id      location  fault_severity    severity_type     event_type  \
0  14121  location 118               1  severity_type 2  event_type 34   
1  14121  location 118               1  severity_type 2  event_type 34   
2  14121  location 118               1  severity_type 2  event_type 35   
3  14121  location 118               1  severity_type 2  event_type 35   
4   9320   location 91               0  severity_type 2  event_type 34   

   log_feature  volume    resource_type  
0  feature 312      19  resource_type 2  
1  feature 232      19  resource_type 2  
2  feature 312      19  resource_type 2  
3  feature 232      19  resource_type 2  
4  feature 315     200  resource_type 2

In [13]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61839 entries, 0 to 61838
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   id              61839 non-null  int64 
 1   location        61839 non-null  object
 2   fault_severity  61839 non-null  int64 
 3   severity_type   61839 non-null  object
 4   event_type      61839 non-null  object
 5   log_feature     61839 non-null  object
 6   volume          61839 non-null  int64 
 7   resource_type   61839 non-null  object
dtypes: int64(3), object(5)
memory usage: 4.2+ MB


In [14]:
Train.shape

(61839, 8)

In [15]:
Train.describe()

id  fault_severity        volume
count  61839.000000    61839.000000  61839.000000
mean    9104.379469        0.549168      8.390336
std     5387.274195        0.727701     22.902491
min        1.000000        0.000000      1.000000
25%     4353.000000        0.000000      1.000000
50%     8981.000000        0.000000      2.000000
75%    13664.000000        1.000000      6.000000
max    18550.000000        2.000000    877.000000

## Data Preparation

In [16]:
Train.drop_duplicates(subset = "id", keep = "first", inplace = True) 


In [17]:
Train.head()

id      location  fault_severity    severity_type     event_type  \
0   14121  location 118               1  severity_type 2  event_type 34   
4    9320   location 91               0  severity_type 2  event_type 34   
8   14394  location 152               1  severity_type 2  event_type 35   
12   8218  location 931               1  severity_type 1  event_type 15   
18  14804  location 120               0  severity_type 1  event_type 34   

    log_feature  volume    resource_type  
0   feature 312      19  resource_type 2  
4   feature 315     200  resource_type 2  
8   feature 221       1  resource_type 2  
12   feature 80       9  resource_type 8  
18  feature 134       1  resource_type 2

In [18]:
# df['Year_Job'] = df['Years in current job'].astype('str').str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)
liste = list(Train)
print(liste)
for i in Train:
    Train[i] = Train[i].astype('str').str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)
    

['id', 'location', 'fault_severity', 'severity_type', 'event_type', 'log_feature', 'volume', 'resource_type']


In [19]:
Train.head()

id  location  fault_severity  severity_type  event_type  log_feature  \
0   14121       118               1              2          34          312   
4    9320        91               0              2          34          315   
8   14394       152               1              2          35          221   
12   8218       931               1              1          15           80   
18  14804       120               0              1          34          134   

    volume  resource_type  
0       19              2  
4      200              2  
8        1              2  
12       9              8  
18       1              2

In [20]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7381 entries, 0 to 61836
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              7381 non-null   int32
 1   location        7381 non-null   int32
 2   fault_severity  7381 non-null   int32
 3   severity_type   7381 non-null   int32
 4   event_type      7381 non-null   int32
 5   log_feature     7381 non-null   int32
 6   volume          7381 non-null   int32
 7   resource_type   7381 non-null   int32
dtypes: int32(8)
memory usage: 288.3 KB


In [21]:
Train["log_feature"].unique()

array([312, 315, 221,  80, 134, 171, 374, 235,  71, 136,  68, 167, 232,
        82, 163, 378, 202,  73,  54, 170, 193, 201, 203,  55, 195,  74,
        76, 291, 306, 375, 307, 290,  81, 313, 360, 101, 223, 181, 283,
       117,  77, 234,  75, 233, 301, 219, 345, 309, 273, 376, 209, 314,
        56,  51, 206, 158, 196,  83,  42, 109, 135, 204,  87, 207,  70,
        18, 191, 227, 228, 178,  65, 217, 161, 368,  44,  66, 230, 211,
       229, 188, 160, 172, 308, 305, 220, 239, 349, 198, 285, 369, 244,
       310,  26, 108,  62,  41,  85, 154, 205,  52, 144, 362, 182, 118,
        15, 284,  27,  47, 141, 276,  63, 354, 289,  40, 197, 169, 280,
       302, 317,  11, 218, 111, 365,  84, 137, 318, 316, 133,  94, 179,
       222,  39, 165, 183, 359,  90, 293,  53,  37, 131, 153,   1, 330,
        61, 240,  99,  86, 267, 159, 156,   2, 303,  78, 328, 370,  30,
       115, 384, 353,  45, 157,  10, 311,  64,  95, 168, 155, 277, 103,
       150, 237,  29,  69,   8, 200,  25, 187, 279, 149, 292,  6

In [22]:
Train["location"].unique()

array([ 118,   91,  152,  931,  120,  664,  640,  122,  263,  613,  760,
        519,  746, 1066,  812,  343,  133,  976,  948,  808,  894,  875,
       1024,  166,  687, 1016,  707,  978,  775,  829,  732,  508,  257,
        116,  830,  491,  253,  740,  704, 1089,  653,  600,  892,  802,
        794,  477,  684,  895,  496,  321, 1107, 1086, 1099,  975, 1019,
        342,  744,  181, 1052,  696, 1008,  798,  777,   95,  699,  272,
        846,  795,  826,  112,  778,  810,  690,  494, 1095,  445,  478,
        661,  380,  242, 1082, 1007,  131,  980,  373,  169,  421,  779,
         59,  648,  124,    7,   12, 1026,  270, 1106, 1090,  522,  836,
        145, 1020,  804, 1055,  157,  893,  457,   99,  839,  719,  793,
       1109,  957,  665,  646,  302,  273,    1,  476,  734, 1076,  520,
       1046,  803,  963,  821, 1061,  714,  300,  611,  724,  173,  943,
        733,  249,  408,  723,  255,  655,  888,  989, 1015,  692,  945,
        651,  763,  416,  497,  890,  849,  208,  1

In [23]:
Train["event_type"].unique()

array([34, 35, 15, 11, 50, 54, 44, 20, 42, 23, 14, 10, 13, 22, 18, 43, 21,
       29, 40, 39, 24, 32, 47, 46,  2, 27,  9,  5, 26, 45,  7,  8, 38, 30,
        6, 28,  3, 31, 51, 12, 49, 48, 36, 25, 53])

In [24]:
Train["resource_type"].unique()

array([ 2,  8,  7,  4,  6,  9,  1,  3, 10,  5])

In [25]:
liste = ["log_feature","location"]
for i in liste:
    Train[i] = Train[i].astype("category")

In [26]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7381 entries, 0 to 61836
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype   
---  ------          --------------  -----   
 0   id              7381 non-null   int32   
 1   location        7381 non-null   category
 2   fault_severity  7381 non-null   int32   
 3   severity_type   7381 non-null   int32   
 4   event_type      7381 non-null   int32   
 5   log_feature     7381 non-null   category
 6   volume          7381 non-null   int32   
 7   resource_type   7381 non-null   int32   
dtypes: category(2), int32(6)
memory usage: 308.9 KB


## Modeling

In [27]:
df_dummies = pd.get_dummies(Train,drop_first = True)
df_dummies.shape

(7381, 1156)

In [28]:
x = df_dummies.drop(["id","fault_severity"], axis = 1)

In [29]:
y = Train["fault_severity"]

In [30]:
x.shape, y.shape

((7381, 1154), (7381,))

In [31]:
def classification(x,y):
    from sklearn.naive_bayes import GaussianNB
    from sklearn.naive_bayes import BernoulliNB
    from sklearn.svm import SVC
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.linear_model import LogisticRegression
    
    from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
    from sklearn.metrics import confusion_matrix,classification_report
    from sklearn.model_selection import train_test_split
       
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

    g=GaussianNB()
    b=BernoulliNB()
    KN=KNeighborsClassifier()
    SVC=SVC() 
    D=DecisionTreeClassifier()
    R=RandomForestClassifier()
    Log=LogisticRegression()
    
    algos=[g,b,KN,SVC,D,R,Log]
    algo_names=['GaussianNB','BernoulliNB','KNeighborsClassifier','SVC','DecisionTreeClassifier','RandomForestClassifier','LogisticRegression']
   
    accuracy_scored=[]

    
    for item in algos:
        item.fit(x_train,y_train)
        item.predict(x_test)
        
        accuracy_scored.append(accuracy_score(y_test,item.predict(x_test)))
       
    result=pd.DataFrame(columns=['accuracy_score'],index=algo_names)
    result['accuracy_score']=accuracy_scored
    return result.sort_values('accuracy_score',ascending=False)

In [32]:
classification(x,y)

accuracy_score
LogisticRegression            0.696682
RandomForestClassifier        0.693974
KNeighborsClassifier          0.684496
BernoulliNB                   0.681787
DecisionTreeClassifier        0.670278
SVC                           0.643873
GaussianNB                    0.480704

### Prediction

In [43]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
R=RandomForestClassifier()
R.fit(x_train,y_train)

RandomForestClassifier()

In [45]:
y_pred = R.predict(x_test)

In [46]:
accuracy_score(y_test,y_pred)

0.6960054163845633

In [47]:
y_pred

array([0, 0, 2, ..., 1, 0, 1])

In [50]:
Train['fault_severity'].value_counts()

0    4784
1    1871
2     726
Name: fault_severity, dtype: int64

In [53]:
R=RandomForestClassifier()
R.fit(x,y)

RandomForestClassifier()

In [54]:
prediction = R.predict(x)

In [56]:
Train.loc[:,'fault severity prediction'] = prediction
Train.head()

id location  fault_severity  severity_type  event_type log_feature  \
0   14121      118               1              2          34         312   
4    9320       91               0              2          34         315   
8   14394      152               1              2          35         221   
12   8218      931               1              1          15          80   
18  14804      120               0              1          34         134   

    volume  resource_type  Fault Severity Prediction  \
0       19              2                          1   
4      200              2                          0   
8        1              2                          1   
12       9              8                          1   
18       1              2                          0   

    fault severity prediction  
0                           1  
4                           0  
8                           1  
12                          1  
18                          0

In [58]:
output = pd.DataFrame({'ID': Train.id, 'Fault Severity': prediction})
output.shape

(7381, 2)

In [59]:
output.to_csv("service_disruption_prediction.csv",index = False)